/*
 * =====================================================================
 *
 *			XplicitNgin
 *			Copyright XPX, all rights reserved.
 *
 *			File: App.cpp
 *			Purpose: Application Implementation
 *
 * =====================================================================
 */

#include "LoadingInstance.h"
#include "App.h"

namespace Xplicit::App
{
	Application::Application()
		: m_wsa(), m_data_path("")
	{
		XPLICIT_GET_DATA_DIR(data_tmp);

		memcpy_s(m_data_path, 4096, data_tmp, 4096);

		if (*m_data_path == 0)
			throw std::runtime_error("getenv: no such variable!");

		Xplicit::init_winsock(&m_wsa);

#ifdef XPLICIT_DEBUG
		Xplicit::open_terminal();
#endif

		this->setup_xml();
		this->setup_manifest();
	}

	Application::~Application()
	{
		if (!InstanceManager::get_singleton_ptr())
			return;

		InstanceManager::get_singleton_ptr()->remove<NetworkInstance>("NetworkInstance");
		InstanceManager::get_singleton_ptr()->remove<Client::CameraInstance>("CameraInstance");
		InstanceManager::get_singleton_ptr()->remove<Client::LocalActor>("LocalActor");
		EventDispatcher::get_singleton_ptr()->remove<Client::LocalActorMoveEvent>("LocalActorMoveEvent");
	}

	void Application::setup_xml()
	{
		std::string path = m_data_path;
		path += "\\MANIFEST.xml";

		XML = IRR->getFileSystem()->createXMLReaderUTF8(path.c_str());
	}

	void Application::setup_manifest()
	{
		if (!XML)
			throw std::runtime_error("No XML provided..");

		char ip[128];

		// read until EOF.
		while (XML->read())
		{
			switch (XML->getNodeType())
			{
			//we found a new element
			case irr::io::EXN_ELEMENT:
			{
				if (std::string(XML->getNodeName()) == "CONNECT")
				{
					if (strlen(XML->getAttributeValue("IP")) > 128)
						throw EngineError();

					memcpy(ip, XML->getAttributeValue("IP"), strlen(XML->getAttributeValue("IP")));
					ip[strlen(XML->getAttributeValue("IP"))] = 0;

#ifdef XPLICIT_DEBUG
					XPLICIT_INFO("Connecting to server: " + std::string(XML->getAttributeValue("IP")));
#endif
				}

				break;
			}
			}
		}

		auto loader = InstanceManager::get_singleton_ptr()->add<Client::LoadingInstance>();
		assert(loader);

		XPLICIT_INFO(ip);
		loader->connect(ip);
	}

	// Application Settings

	static const char* XPLICIT_DEFAULT_SETTINGS = "<!-- XplicitNgin Settings -->\r\n<Window>\r\n<Dim Width = \"800\" Height = \"600\" />\r\n<MouseSpeed Value=\"1.0\"/>\r\n</Window>";

	Application::Settings::Settings()
		: m_settings_path()
	{
		XPLICIT_GET_DATA_DIR(dat);

		m_settings_path = dat;
		m_settings_path += "\\SETTINGS.xml";

		assert(!m_settings_path.empty());

		m_xml_reader = IRR->getFileSystem()->createXMLReaderUTF8(m_settings_path.c_str());
		m_xml_writer = IRR->getFileSystem()->createXMLWriterUTF8(m_settings_path.c_str());
	}

	Application::Settings::~Settings()
	{

	}

	void Application::Settings::write(Application::Settings::Traits& traits)
	{
		assert(m_xml_writer);

		if (m_xml_writer)
		{
			m_xml_writer->writeComment("Generated by XplicitPlayer --> www.xplicit.com");
			m_xml_writer->writeLineBreak();

			m_xml_writer->writeElement("Window");

			m_xml_writer->writeElement("Dim", true, "Width", 
				std::to_string(traits.window_width).c_str(), "Height",
				std::to_string(traits.window_height).c_str());

			m_xml_writer->writeElement("MouseSpeed", true, "Speed",
				std::to_string(traits.mouse_sensitivity).c_str());

			m_xml_writer->writeClosingTag("Window");
		}
	}

	void Application::Settings::read(Application::Settings::Traits& traits)
	{
		assert(m_xml_reader);

		if (m_xml_reader)
		{
			while (m_xml_reader->read())
			{
				switch (m_xml_reader->getNodeType())
				{
				case irr::io::EXN_ELEMENT:
				{

					break;
				}
				}
			}
		}
	}
}