/*
 * =====================================================================
 *
 *			XplicitNgin
 *			Copyright XPX, all rights reserved.
 *
 *			File: App.cpp
 *			Purpose: Application Implementation
 *
 * =====================================================================
 */

#include "App.h"

namespace Xplicit::App
{
	Application::Application()
		: m_settings(), m_wsa(), m_data_path("")
	{
		XPLICIT_GET_DATA_DIR(data_tmp);

		m_data_path += data_tmp;

		assert(!m_data_path.empty());

#ifdef XPLICIT_WINDOWS
		Xplicit::init_winsock(&m_wsa);
#endif

#ifdef XPLICIT_DEBUG
		Xplicit::open_terminal();
#endif

		this->setup();
		this->setup_paths();
		this->read_manifest();
	}

	Application::~Application()
	{

	}

	void Application::setup_paths()
	{
		std::string path = m_data_path;
		path += "\\MANIFEST.xml";

		XML = IRR->getFileSystem()->createXMLReaderUTF8(path.c_str());
	}

	void Application::read_manifest()
	{
		if (!XML)
			throw std::runtime_error("No XML provided..");

		char ip[128];

		// read until EOF.
		while (XML->read())
		{
			switch (XML->getNodeType())
			{
			//we found a new element
			case irr::io::EXN_ELEMENT:
			{
				if (std::string(XML->getNodeName()) == "CONNECT")
				{
					if (strlen(XML->getAttributeValue("IP")) > 128)
						throw EngineError();

					memcpy(ip, XML->getAttributeValue("IP"), strlen(XML->getAttributeValue("IP")));
					ip[strlen(XML->getAttributeValue("IP"))] = 0;

#ifdef XPLICIT_DEBUG
					XPLICIT_INFO("Connecting to server: " + std::string(XML->getAttributeValue("IP")));
#endif
				}

				break;
			}
			}
		}

		auto loader = InstanceManager::get_singleton_ptr()->add<Client::LoadingInstance>();
		XPLICIT_ASSERT(loader);

		loader->connect(ip);
	}

	void Application::setup()
	{
		Xplicit::ApplicationContext::get_singleton().set(new Xplicit::InputReceiver());

		if (!KB)
			throw std::bad_alloc();

#ifdef XPLICIT_WINDOWS

		Xplicit::ApplicationContext::get_singleton().set(irr::createDevice(irr::video::EDT_DIRECT3D9,
			Xplicit::Client::XPLICIT_DIM,
			32U,
			false,
			false,
			false,
			KB));

		HMENU menuHandle = GetSystemMenu((HWND)IRR->getVideoDriver()->getExposedVideoData().D3D9.HWnd, FALSE);
		EnableMenuItem(menuHandle, SC_CLOSE, MF_GRAYED);

#endif

		m_settings = std::make_unique<Settings>();
		assert(m_settings);

		Settings::Traits traits{};
		m_settings->read(traits);

		if (traits.window_width >= 800 && traits.window_width >= 600) 
			IRR->setWindowSize(dimension2d<irr::u32>(traits.window_width, traits.window_height));

		IRR->setWindowCaption(Xplicit::App::XPLICIT_APP_NAME);
	}

	// Application Settings

	static const char* XPLICIT_DEFAULT_SETTINGS = "<!-- XplicitNgin Settings -->\r\n<Window>\r\n<Dim Width = \"800\" Height = \"600\" />\r\n<MouseSpeed Value=\"1.0\"/>\r\n</Window>";

	Application::Settings::Settings()
		: m_settings_path(), m_xml_reader(nullptr), m_xml_writer(nullptr)
	{
		XPLICIT_GET_DATA_DIR(dat);

		m_settings_path = dat;
		m_settings_path += "\\SETTINGS.xml";

		assert(!m_settings_path.empty());

		m_xml_reader = IRR->getFileSystem()->createXMLReaderUTF8(m_settings_path.c_str());
		m_xml_writer = IRR->getFileSystem()->createXMLWriterUTF8(m_settings_path.c_str());
	}

	Application::Settings::~Settings()
	{
		if (m_xml_writer)
			m_xml_writer->drop();

		if (m_xml_reader)
			m_xml_reader->drop();
	}

	void Application::Settings::write(Application::Settings::Traits& traits)
	{
		if (m_xml_writer)
		{
			m_xml_writer->writeComment("Generated by XplicitPlayer --> www.xplicit.com");
			m_xml_writer->writeLineBreak();

			m_xml_writer->writeElement("Window");

			m_xml_writer->writeElement("Dim", true, "Width", 
				std::to_string(traits.window_width).c_str(), "Height",
				std::to_string(traits.window_height).c_str());

			m_xml_writer->writeClosingTag("Window");
		}
	}

	void Application::Settings::read(Application::Settings::Traits& traits)
	{
		if (m_xml_reader)
		{
			while (m_xml_reader->read())
			{
				switch (m_xml_reader->getNodeType())
				{
				case irr::io::EXN_ELEMENT:
				{

					break;
				}
				}
			}
		}
	}
}